# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], max_length=8, verbose_name='animal type')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pet',
                'verbose_name_plural': 'pets',
                'ordering': ['owner', 'birthday', 'name', 'pk'],
            },
        ),
    ]
